import pytest
from responses import RequestsMock

from tests import loader


@pytest.fixture
def vba_keywords_service(responses: RequestsMock):
    responses.add(
        responses.GET,
        url="http://localhost:8949/",
        json={
            "swagger": "2.0",
            "definitions": {
                "VBAKeywords": {
                    "properties": {
                        "addhandler": {},
                        "addressof": {},
                        "alias": {},
                        "and": {},
                        "andalso": {},
                        "as": {},
                        "attribute": {},
                        "boolean": {},
                        "byref": {},
                        "byte": {},
                        "byval": {},
                        "call": {},
                        "case": {},
                        "catch": {},
                        "cbool": {},
                        "cbyte": {},
                        "cchar": {},
                        "cdate": {},
                        "cdbl": {},
                        "cdec": {},
                        "char": {},
                        "cint": {},
                        "class": {},
                        "clng": {},
                        "cobj": {},
                        "const": {},
                        "continue": {},
                        "csbyte": {},
                        "cshort": {},
                        "csng": {},
                        "cstr": {},
                        "ctype": {},
                        "cuint": {},
                        "culng": {},
                        "currency": {},
                        "cushort": {},
                        "date": {},
                        "decimal": {},
                        "declare": {},
                        "default": {},
                        "delegate": {},
                        "dim": {},
                        "directcast": {},
                        "do": {},
                        "double": {},
                        "each": {},
                        "else": {},
                        "elseif": {},
                        "end": {},
                        "endif": {},
                        "enum": {},
                        "erase": {},
                        "error": {},
                        "event": {},
                        "exit": {},
                        "finally": {},
                        "for": {},
                        "friend": {},
                        "function": {},
                        "get": {},
                        "gettype": {},
                        "getxmlnamespace": {},
                        "global": {},
                        "gosub": {},
                        "goto": {},
                        "handles": {},
                        "if": {},
                        "implements": {},
                        "imports": {},
                        "in": {},
                        "inherits": {},
                        "integer": {},
                        "interface": {},
                        "is": {},
                        "isnot": {},
                        "let": {},
                        "lib": {},
                        "like": {},
                        "long": {},
                        "loop": {},
                        "me": {},
                        "mod": {},
                        "module": {},
                        "mustinherit": {},
                        "mustoverride": {},
                        "mybase": {},
                        "myclass": {},
                        "namespace": {},
                        "narrowing": {},
                        "new": {},
                        "next": {},
                        "not": {},
                        "nothing": {},
                        "notinheritable": {},
                        "notoverridable": {},
                        "object": {},
                        "of": {},
                        "on": {},
                        "operator": {},
                        "option": {},
                        "optional": {},
                        "or": {},
                        "orelse": {},
                        "overloads": {},
                        "overridable": {},
                        "overrides": {},
                        "paramarray": {},
                        "partial": {},
                        "private": {},
                        "property": {},
                        "protected": {},
                        "public": {},
                        "raiseevent": {},
                        "readonly": {},
                        "redim": {},
                        "rem": {},
                        "removehandler": {},
                        "resume": {},
                        "return": {},
                        "sbyte": {},
                        "select": {},
                        "set": {},
                        "shadows": {},
                        "shared": {},
                        "short": {},
                        "single": {},
                        "static": {},
                        "step": {},
                        "stop": {},
                        "string": {},
                        "structure": {},
                        "sub": {},
                        "synclock": {},
                        "then": {},
                        "throw": {},
                        "to": {},
                        "try": {},
                        "trycast": {},
                        "type": {},
                        "typeof": {},
                        "uinteger": {},
                        "ulong": {},
                        "ushort": {},
                        "using": {},
                        "variant": {},
                        "wend": {},
                        "when": {},
                        "while": {},
                        "widening": {},
                        "with": {},
                        "withevents": {},
                        "writeonly": {},
                        "xor": {},
                    }
                },
                "PythonKeywords": {"properties": {"with.a.dot": {}}},
            },
            "produces": ["application/json"],
            "paths": {
                "/vba_restricted_keywords": {
                    "parameters": [
                        {
                            "description": "",
                            "in": "query",
                            "name": "addhandler",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "addressof",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "alias",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "and",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "andalso",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "as",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "attribute",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "boolean",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "byref",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "byte",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "byval",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "call",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "case",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "catch",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cbool",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cbyte",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cchar",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cdate",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cdbl",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cdec",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "char",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cint",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "class",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "clng",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cobj",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "const",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "continue",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "csbyte",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cshort",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "csng",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cstr",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "ctype",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cuint",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "culng",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "currency",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "cushort",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "date",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "decimal",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "declare",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "default",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "delegate",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "dim",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "directcast",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "do",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "double",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "each",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "else",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "elseif",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "end",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "endif",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "enum",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "erase",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "error",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "event",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "exit",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "finally",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "for",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "friend",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "function",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "get",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "gettype",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "getxmlnamespace",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "global",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "gosub",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "goto",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "handles",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "if",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "implements",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "imports",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "in",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "inherits",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "integer",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "interface",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "is",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "isnot",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "let",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "lib",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "like",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "long",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "loop",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "me",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "mod",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "module",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "mustinherit",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "mustoverride",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "mybase",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "myclass",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "namespace",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "narrowing",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "new",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "next",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "not",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "nothing",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "notinheritable",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "notoverridable",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "object",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "of",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "on",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "operator",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "option",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "optional",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "or",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "orelse",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "overloads",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "overridable",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "overrides",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "paramarray",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "partial",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "private",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "property",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "protected",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "public",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "raiseevent",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "readonly",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "redim",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "rem",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "removehandler",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "resume",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "return",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "sbyte",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "select",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "set",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "shadows",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "shared",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "short",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "single",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "static",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "step",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "stop",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "string",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "structure",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "sub",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "synclock",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "then",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "throw",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "to",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "try",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "trycast",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "type",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "typeof",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "uinteger",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "ulong",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "ushort",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "using",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "variant",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "wend",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "when",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "while",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "widening",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "with",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "withevents",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "writeonly",
                            "required": True,
                            "type": "string",
                        },
                        {
                            "description": "",
                            "in": "query",
                            "name": "xor",
                            "required": True,
                            "type": "string",
                        },
                    ],
                    "get": {
                        "operationId": "get_vba_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "schema": {"$ref": "#/definitions/VBAKeywords"},
                            }
                        },
                    },
                    "post": {
                        "operationId": "post_vba_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "$ref": "#/definitions/VBAKeywords",
                            }
                        },
                        "produces": ["application/json"],
                    },
                    "put": {
                        "operationId": "put_vba_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "$ref": "#/definitions/VBAKeywords",
                            }
                        },
                        "produces": ["application/json"],
                    },
                    "delete": {
                        "operationId": "delete_vba_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "$ref": "#/definitions/VBAKeywords",
                            }
                        },
                        "produces": ["application/json"],
                    },
                },
                "/{attribute}/vba/restricted/keyword/in/uri/parameter": {
                    "parameters": [
                        {
                            "type": "string",
                            "in": "path",
                            "name": "attribute",
                            "description": "attribute uri param",
                            "required": True,
                        }
                    ],
                    "get": {
                        "operationId": "get_attribute_vba_restricted_keyword_in_uri_parameter",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "schema": {"$ref": "#/definitions/VBAKeywords"},
                            }
                        },
                    },
                },
                "/python_restricted_keywords": {
                    "parameters": [
                        {
                            "description": "",
                            "in": "query",
                            "name": "with.a.dot",
                            "required": True,
                            "type": "string",
                        }
                    ],
                    "get": {
                        "operationId": "get_python_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "schema": {"$ref": "#/definitions/PythonKeywords"},
                            }
                        },
                    },
                    "post": {
                        "operationId": "post_python_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "$ref": "#/definitions/PythonKeywords",
                            }
                        },
                        "produces": ["application/json"],
                    },
                    "put": {
                        "operationId": "put_python_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "$ref": "#/definitions/PythonKeywords",
                            }
                        },
                        "produces": ["application/json"],
                    },
                    "delete": {
                        "operationId": "delete_python_restricted_keywords",
                        "responses": {
                            "200": {
                                "description": "return value",
                                "$ref": "#/definitions/PythonKeywords",
                            }
                        },
                        "produces": ["application/json"],
                    },
                },
            },
        },
        match_querystring=True,
    )


def test_get_vba_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.GET,
        url="http://localhost:8949/vba_restricted_keywords?addhandler=addhandler+value&addressof=addressof+value&alias=alias+value&and=and+value&andalso=andalso+value&as=as+value&attribute=attribute+value&boolean=boolean+value&byref=byref+value&byte=byte+value&byval=byval+value&call=call+value&case=case+value&catch=catch+value&cbool=cbool+value&cbyte=cbyte+value&cchar=cchar+value&cdate=cdate+value&cdbl=cdbl+value&cdec=cdec+value&char=char+value&cint=cint+value&class=class+value&clng=clng+value&cobj=cobj+value&const=const+value&continue=continue+value&csbyte=csbyte+value&cshort=cshort+value&csng=csng+value&cstr=cstr+value&ctype=ctype+value&cuint=cuint+value&culng=culng+value&currency=currency+value&cushort=cushort+value&date=date+value&decimal=decimal+value&declare=declare+value&default=default+value&delegate=delegate+value&dim=dim+value&directcast=directcast+value&do=do+value&double=double+value&each=each+value&else=else+value&elseif=elseif+value&end=end+value&endif=endif+value&enum=enum+value&erase=erase+value&error=error+value&event=event+value&exit=exit+value&finally=finally+value&for=for+value&friend=friend+value&function=function+value&get=get+value&gettype=gettype+value&getxmlnamespace=getxmlnamespace+value&global=global+value&gosub=gosub+value&goto=goto+value&handles=handles+value&if=if+value&implements=implements+value&imports=imports+value&in=in+value&inherits=inherits+value&integer=integer+value&interface=interface+value&is=is+value&isnot=isnot+value&let=let+value&lib=lib+value&like=like+value&long=long+value&loop=loop+value&me=me+value&mod=mod+value&module=module+value&mustinherit=mustinherit+value&mustoverride=mustoverride+value&mybase=mybase+value&myclass=myclass+value&namespace=namespace+value&narrowing=narrowing+value&new=new+value&next=next+value&not=not+value&nothing=nothing+value&notinheritable=notinheritable+value&notoverridable=notoverridable+value&object=object+value&of=of+value&on=on+value&operator=operator+value&option=option+value&optional=optional+value&or=or+value&orelse=orelse+value&overloads=overloads+value&overridable=overridable+value&overrides=overrides+value&paramarray=paramarray+value&partial=partial+value&private=private+value&property=property+value&protected=protected+value&public=public+value&raiseevent=raiseevent+value&readonly=readonly+value&redim=redim+value&rem=rem+value&removehandler=removehandler+value&resume=resume+value&return=return+value&sbyte=sbyte+value&select=select+value&set=set+value&shadows=shadows+value&shared=shared+value&short=short+value&single=single+value&static=static+value&step=step+value&stop=stop+value&string=string+value&structure=structure+value&sub=sub+value&synclock=synclock+value&then=then+value&throw=throw+value&to=to+value&try=try+value&trycast=trycast+value&type=type+value&typeof=typeof+value&uinteger=uinteger+value&ulong=ulong+value&ushort=ushort+value&using=using+value&variant=variant+value&wend=wend+value&when=when+value&while=while+value&widening=widening+value&with=with+value&withevents=withevents+value&writeonly=writeonly+value&xor=xor+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_get_vba_restricted_keywords(
        addhandler_visual_basic="addhandler value",
        addressof_visual_basic="addressof value",
        alias_visual_basic="alias value",
        and_visual_basic="and value",
        andalso_visual_basic="andalso value",
        as_visual_basic="as value",
        attribute_visual_basic="attribute value",
        boolean_visual_basic="boolean value",
        byref_visual_basic="byref value",
        byte_visual_basic="byte value",
        byval_visual_basic="byval value",
        call_visual_basic="call value",
        case_visual_basic="case value",
        catch_visual_basic="catch value",
        cbool_visual_basic="cbool value",
        cbyte_visual_basic="cbyte value",
        cchar_visual_basic="cchar value",
        cdate_visual_basic="cdate value",
        cdbl_visual_basic="cdbl value",
        cdec_visual_basic="cdec value",
        char_visual_basic="char value",
        cint_visual_basic="cint value",
        class_visual_basic="class value",
        clng_visual_basic="clng value",
        cobj_visual_basic="cobj value",
        const_visual_basic="const value",
        continue_visual_basic="continue value",
        csbyte_visual_basic="csbyte value",
        cshort_visual_basic="cshort value",
        csng_visual_basic="csng value",
        cstr_visual_basic="cstr value",
        ctype_visual_basic="ctype value",
        cuint_visual_basic="cuint value",
        culng_visual_basic="culng value",
        currency_visual_basic="currency value",
        cushort_visual_basic="cushort value",
        date_visual_basic="date value",
        decimal_visual_basic="decimal value",
        declare_visual_basic="declare value",
        default_visual_basic="default value",
        delegate_visual_basic="delegate value",
        dim_visual_basic="dim value",
        directcast_visual_basic="directcast value",
        do_visual_basic="do value",
        double_visual_basic="double value",
        each_visual_basic="each value",
        else_visual_basic="else value",
        elseif_visual_basic="elseif value",
        end_visual_basic="end value",
        endif_visual_basic="endif value",
        enum_visual_basic="enum value",
        erase_visual_basic="erase value",
        error_visual_basic="error value",
        event_visual_basic="event value",
        exit_visual_basic="exit value",
        finally_visual_basic="finally value",
        for_visual_basic="for value",
        friend_visual_basic="friend value",
        function_visual_basic="function value",
        get_visual_basic="get value",
        gettype_visual_basic="gettype value",
        getxmlnamespace_visual_basic="getxmlnamespace value",
        global_visual_basic="global value",
        gosub_visual_basic="gosub value",
        goto_visual_basic="goto value",
        handles_visual_basic="handles value",
        if_visual_basic="if value",
        implements_visual_basic="implements value",
        imports_visual_basic="imports value",
        in_visual_basic="in value",
        inherits_visual_basic="inherits value",
        integer_visual_basic="integer value",
        interface_visual_basic="interface value",
        is_visual_basic="is value",
        isnot_visual_basic="isnot value",
        let_visual_basic="let value",
        lib_visual_basic="lib value",
        like_visual_basic="like value",
        long_visual_basic="long value",
        loop_visual_basic="loop value",
        me_visual_basic="me value",
        mod_visual_basic="mod value",
        module_visual_basic="module value",
        mustinherit_visual_basic="mustinherit value",
        mustoverride_visual_basic="mustoverride value",
        mybase_visual_basic="mybase value",
        myclass_visual_basic="myclass value",
        namespace_visual_basic="namespace value",
        narrowing_visual_basic="narrowing value",
        new_visual_basic="new value",
        next_visual_basic="next value",
        not_visual_basic="not value",
        nothing_visual_basic="nothing value",
        notinheritable_visual_basic="notinheritable value",
        notoverridable_visual_basic="notoverridable value",
        object_visual_basic="object value",
        of_visual_basic="of value",
        on_visual_basic="on value",
        operator_visual_basic="operator value",
        option_visual_basic="option value",
        optional_visual_basic="optional value",
        or_visual_basic="or value",
        orelse_visual_basic="orelse value",
        overloads_visual_basic="overloads value",
        overridable_visual_basic="overridable value",
        overrides_visual_basic="overrides value",
        paramarray_visual_basic="paramarray value",
        partial_visual_basic="partial value",
        private_visual_basic="private value",
        property_visual_basic="property value",
        protected_visual_basic="protected value",
        public_visual_basic="public value",
        raiseevent_visual_basic="raiseevent value",
        readonly_visual_basic="readonly value",
        redim_visual_basic="redim value",
        rem_visual_basic="rem value",
        removehandler_visual_basic="removehandler value",
        resume_visual_basic="resume value",
        return_visual_basic="return value",
        sbyte_visual_basic="sbyte value",
        select_visual_basic="select value",
        set_visual_basic="set value",
        shadows_visual_basic="shadows value",
        shared_visual_basic="shared value",
        short_visual_basic="short value",
        single_visual_basic="single value",
        static_visual_basic="static value",
        step_visual_basic="step value",
        stop_visual_basic="stop value",
        string_visual_basic="string value",
        structure_visual_basic="structure value",
        sub_visual_basic="sub value",
        synclock_visual_basic="synclock value",
        then_visual_basic="then value",
        throw_visual_basic="throw value",
        to_visual_basic="to value",
        try_visual_basic="try value",
        trycast_visual_basic="trycast value",
        type_visual_basic="type value",
        typeof_visual_basic="typeof value",
        uinteger_visual_basic="uinteger value",
        ulong_visual_basic="ulong value",
        ushort_visual_basic="ushort value",
        using_visual_basic="using value",
        variant_visual_basic="variant value",
        wend_visual_basic="wend value",
        when_visual_basic="when value",
        while_visual_basic="while value",
        widening_visual_basic="widening value",
        with_visual_basic="with value",
        withevents_visual_basic="withevents value",
        writeonly_visual_basic="writeonly value",
        xor_visual_basic="xor value",
    ) == [[""]]


def test_post_vba_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.POST,
        url="http://localhost:8949/vba_restricted_keywords?addhandler=addhandler+value&addressof=addressof+value&alias=alias+value&and=and+value&andalso=andalso+value&as=as+value&attribute=attribute+value&boolean=boolean+value&byref=byref+value&byte=byte+value&byval=byval+value&call=call+value&case=case+value&catch=catch+value&cbool=cbool+value&cbyte=cbyte+value&cchar=cchar+value&cdate=cdate+value&cdbl=cdbl+value&cdec=cdec+value&char=char+value&cint=cint+value&class=class+value&clng=clng+value&cobj=cobj+value&const=const+value&continue=continue+value&csbyte=csbyte+value&cshort=cshort+value&csng=csng+value&cstr=cstr+value&ctype=ctype+value&cuint=cuint+value&culng=culng+value&currency=currency+value&cushort=cushort+value&date=date+value&decimal=decimal+value&declare=declare+value&default=default+value&delegate=delegate+value&dim=dim+value&directcast=directcast+value&do=do+value&double=double+value&each=each+value&else=else+value&elseif=elseif+value&end=end+value&endif=endif+value&enum=enum+value&erase=erase+value&error=error+value&event=event+value&exit=exit+value&finally=finally+value&for=for+value&friend=friend+value&function=function+value&get=get+value&gettype=gettype+value&getxmlnamespace=getxmlnamespace+value&global=global+value&gosub=gosub+value&goto=goto+value&handles=handles+value&if=if+value&implements=implements+value&imports=imports+value&in=in+value&inherits=inherits+value&integer=integer+value&interface=interface+value&is=is+value&isnot=isnot+value&let=let+value&lib=lib+value&like=like+value&long=long+value&loop=loop+value&me=me+value&mod=mod+value&module=module+value&mustinherit=mustinherit+value&mustoverride=mustoverride+value&mybase=mybase+value&myclass=myclass+value&namespace=namespace+value&narrowing=narrowing+value&new=new+value&next=next+value&not=not+value&nothing=nothing+value&notinheritable=notinheritable+value&notoverridable=notoverridable+value&object=object+value&of=of+value&on=on+value&operator=operator+value&option=option+value&optional=optional+value&or=or+value&orelse=orelse+value&overloads=overloads+value&overridable=overridable+value&overrides=overrides+value&paramarray=paramarray+value&partial=partial+value&private=private+value&property=property+value&protected=protected+value&public=public+value&raiseevent=raiseevent+value&readonly=readonly+value&redim=redim+value&rem=rem+value&removehandler=removehandler+value&resume=resume+value&return=return+value&sbyte=sbyte+value&select=select+value&set=set+value&shadows=shadows+value&shared=shared+value&short=short+value&single=single+value&static=static+value&step=step+value&stop=stop+value&string=string+value&structure=structure+value&sub=sub+value&synclock=synclock+value&then=then+value&throw=throw+value&to=to+value&try=try+value&trycast=trycast+value&type=type+value&typeof=typeof+value&uinteger=uinteger+value&ulong=ulong+value&ushort=ushort+value&using=using+value&variant=variant+value&wend=wend+value&when=when+value&while=while+value&widening=widening+value&with=with+value&withevents=withevents+value&writeonly=writeonly+value&xor=xor+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_post_vba_restricted_keywords(
        addhandler_visual_basic="addhandler value",
        addressof_visual_basic="addressof value",
        alias_visual_basic="alias value",
        and_visual_basic="and value",
        andalso_visual_basic="andalso value",
        as_visual_basic="as value",
        attribute_visual_basic="attribute value",
        boolean_visual_basic="boolean value",
        byref_visual_basic="byref value",
        byte_visual_basic="byte value",
        byval_visual_basic="byval value",
        call_visual_basic="call value",
        case_visual_basic="case value",
        catch_visual_basic="catch value",
        cbool_visual_basic="cbool value",
        cbyte_visual_basic="cbyte value",
        cchar_visual_basic="cchar value",
        cdate_visual_basic="cdate value",
        cdbl_visual_basic="cdbl value",
        cdec_visual_basic="cdec value",
        char_visual_basic="char value",
        cint_visual_basic="cint value",
        class_visual_basic="class value",
        clng_visual_basic="clng value",
        cobj_visual_basic="cobj value",
        const_visual_basic="const value",
        continue_visual_basic="continue value",
        csbyte_visual_basic="csbyte value",
        cshort_visual_basic="cshort value",
        csng_visual_basic="csng value",
        cstr_visual_basic="cstr value",
        ctype_visual_basic="ctype value",
        cuint_visual_basic="cuint value",
        culng_visual_basic="culng value",
        currency_visual_basic="currency value",
        cushort_visual_basic="cushort value",
        date_visual_basic="date value",
        decimal_visual_basic="decimal value",
        declare_visual_basic="declare value",
        default_visual_basic="default value",
        delegate_visual_basic="delegate value",
        dim_visual_basic="dim value",
        directcast_visual_basic="directcast value",
        do_visual_basic="do value",
        double_visual_basic="double value",
        each_visual_basic="each value",
        else_visual_basic="else value",
        elseif_visual_basic="elseif value",
        end_visual_basic="end value",
        endif_visual_basic="endif value",
        enum_visual_basic="enum value",
        erase_visual_basic="erase value",
        error_visual_basic="error value",
        event_visual_basic="event value",
        exit_visual_basic="exit value",
        finally_visual_basic="finally value",
        for_visual_basic="for value",
        friend_visual_basic="friend value",
        function_visual_basic="function value",
        get_visual_basic="get value",
        gettype_visual_basic="gettype value",
        getxmlnamespace_visual_basic="getxmlnamespace value",
        global_visual_basic="global value",
        gosub_visual_basic="gosub value",
        goto_visual_basic="goto value",
        handles_visual_basic="handles value",
        if_visual_basic="if value",
        implements_visual_basic="implements value",
        imports_visual_basic="imports value",
        in_visual_basic="in value",
        inherits_visual_basic="inherits value",
        integer_visual_basic="integer value",
        interface_visual_basic="interface value",
        is_visual_basic="is value",
        isnot_visual_basic="isnot value",
        let_visual_basic="let value",
        lib_visual_basic="lib value",
        like_visual_basic="like value",
        long_visual_basic="long value",
        loop_visual_basic="loop value",
        me_visual_basic="me value",
        mod_visual_basic="mod value",
        module_visual_basic="module value",
        mustinherit_visual_basic="mustinherit value",
        mustoverride_visual_basic="mustoverride value",
        mybase_visual_basic="mybase value",
        myclass_visual_basic="myclass value",
        namespace_visual_basic="namespace value",
        narrowing_visual_basic="narrowing value",
        new_visual_basic="new value",
        next_visual_basic="next value",
        not_visual_basic="not value",
        nothing_visual_basic="nothing value",
        notinheritable_visual_basic="notinheritable value",
        notoverridable_visual_basic="notoverridable value",
        object_visual_basic="object value",
        of_visual_basic="of value",
        on_visual_basic="on value",
        operator_visual_basic="operator value",
        option_visual_basic="option value",
        optional_visual_basic="optional value",
        or_visual_basic="or value",
        orelse_visual_basic="orelse value",
        overloads_visual_basic="overloads value",
        overridable_visual_basic="overridable value",
        overrides_visual_basic="overrides value",
        paramarray_visual_basic="paramarray value",
        partial_visual_basic="partial value",
        private_visual_basic="private value",
        property_visual_basic="property value",
        protected_visual_basic="protected value",
        public_visual_basic="public value",
        raiseevent_visual_basic="raiseevent value",
        readonly_visual_basic="readonly value",
        redim_visual_basic="redim value",
        rem_visual_basic="rem value",
        removehandler_visual_basic="removehandler value",
        resume_visual_basic="resume value",
        return_visual_basic="return value",
        sbyte_visual_basic="sbyte value",
        select_visual_basic="select value",
        set_visual_basic="set value",
        shadows_visual_basic="shadows value",
        shared_visual_basic="shared value",
        short_visual_basic="short value",
        single_visual_basic="single value",
        static_visual_basic="static value",
        step_visual_basic="step value",
        stop_visual_basic="stop value",
        string_visual_basic="string value",
        structure_visual_basic="structure value",
        sub_visual_basic="sub value",
        synclock_visual_basic="synclock value",
        then_visual_basic="then value",
        throw_visual_basic="throw value",
        to_visual_basic="to value",
        try_visual_basic="try value",
        trycast_visual_basic="trycast value",
        type_visual_basic="type value",
        typeof_visual_basic="typeof value",
        uinteger_visual_basic="uinteger value",
        ulong_visual_basic="ulong value",
        ushort_visual_basic="ushort value",
        using_visual_basic="using value",
        variant_visual_basic="variant value",
        wend_visual_basic="wend value",
        when_visual_basic="when value",
        while_visual_basic="while value",
        widening_visual_basic="widening value",
        with_visual_basic="with value",
        withevents_visual_basic="withevents value",
        writeonly_visual_basic="writeonly value",
        xor_visual_basic="xor value",
    ) == [[""]]


def test_put_vba_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.PUT,
        url="http://localhost:8949/vba_restricted_keywords?addhandler=addhandler+value&addressof=addressof+value&alias=alias+value&and=and+value&andalso=andalso+value&as=as+value&attribute=attribute+value&boolean=boolean+value&byref=byref+value&byte=byte+value&byval=byval+value&call=call+value&case=case+value&catch=catch+value&cbool=cbool+value&cbyte=cbyte+value&cchar=cchar+value&cdate=cdate+value&cdbl=cdbl+value&cdec=cdec+value&char=char+value&cint=cint+value&class=class+value&clng=clng+value&cobj=cobj+value&const=const+value&continue=continue+value&csbyte=csbyte+value&cshort=cshort+value&csng=csng+value&cstr=cstr+value&ctype=ctype+value&cuint=cuint+value&culng=culng+value&currency=currency+value&cushort=cushort+value&date=date+value&decimal=decimal+value&declare=declare+value&default=default+value&delegate=delegate+value&dim=dim+value&directcast=directcast+value&do=do+value&double=double+value&each=each+value&else=else+value&elseif=elseif+value&end=end+value&endif=endif+value&enum=enum+value&erase=erase+value&error=error+value&event=event+value&exit=exit+value&finally=finally+value&for=for+value&friend=friend+value&function=function+value&get=get+value&gettype=gettype+value&getxmlnamespace=getxmlnamespace+value&global=global+value&gosub=gosub+value&goto=goto+value&handles=handles+value&if=if+value&implements=implements+value&imports=imports+value&in=in+value&inherits=inherits+value&integer=integer+value&interface=interface+value&is=is+value&isnot=isnot+value&let=let+value&lib=lib+value&like=like+value&long=long+value&loop=loop+value&me=me+value&mod=mod+value&module=module+value&mustinherit=mustinherit+value&mustoverride=mustoverride+value&mybase=mybase+value&myclass=myclass+value&namespace=namespace+value&narrowing=narrowing+value&new=new+value&next=next+value&not=not+value&nothing=nothing+value&notinheritable=notinheritable+value&notoverridable=notoverridable+value&object=object+value&of=of+value&on=on+value&operator=operator+value&option=option+value&optional=optional+value&or=or+value&orelse=orelse+value&overloads=overloads+value&overridable=overridable+value&overrides=overrides+value&paramarray=paramarray+value&partial=partial+value&private=private+value&property=property+value&protected=protected+value&public=public+value&raiseevent=raiseevent+value&readonly=readonly+value&redim=redim+value&rem=rem+value&removehandler=removehandler+value&resume=resume+value&return=return+value&sbyte=sbyte+value&select=select+value&set=set+value&shadows=shadows+value&shared=shared+value&short=short+value&single=single+value&static=static+value&step=step+value&stop=stop+value&string=string+value&structure=structure+value&sub=sub+value&synclock=synclock+value&then=then+value&throw=throw+value&to=to+value&try=try+value&trycast=trycast+value&type=type+value&typeof=typeof+value&uinteger=uinteger+value&ulong=ulong+value&ushort=ushort+value&using=using+value&variant=variant+value&wend=wend+value&when=when+value&while=while+value&widening=widening+value&with=with+value&withevents=withevents+value&writeonly=writeonly+value&xor=xor+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_put_vba_restricted_keywords(
        addhandler_visual_basic="addhandler value",
        addressof_visual_basic="addressof value",
        alias_visual_basic="alias value",
        and_visual_basic="and value",
        andalso_visual_basic="andalso value",
        as_visual_basic="as value",
        attribute_visual_basic="attribute value",
        boolean_visual_basic="boolean value",
        byref_visual_basic="byref value",
        byte_visual_basic="byte value",
        byval_visual_basic="byval value",
        call_visual_basic="call value",
        case_visual_basic="case value",
        catch_visual_basic="catch value",
        cbool_visual_basic="cbool value",
        cbyte_visual_basic="cbyte value",
        cchar_visual_basic="cchar value",
        cdate_visual_basic="cdate value",
        cdbl_visual_basic="cdbl value",
        cdec_visual_basic="cdec value",
        char_visual_basic="char value",
        cint_visual_basic="cint value",
        class_visual_basic="class value",
        clng_visual_basic="clng value",
        cobj_visual_basic="cobj value",
        const_visual_basic="const value",
        continue_visual_basic="continue value",
        csbyte_visual_basic="csbyte value",
        cshort_visual_basic="cshort value",
        csng_visual_basic="csng value",
        cstr_visual_basic="cstr value",
        ctype_visual_basic="ctype value",
        cuint_visual_basic="cuint value",
        culng_visual_basic="culng value",
        currency_visual_basic="currency value",
        cushort_visual_basic="cushort value",
        date_visual_basic="date value",
        decimal_visual_basic="decimal value",
        declare_visual_basic="declare value",
        default_visual_basic="default value",
        delegate_visual_basic="delegate value",
        dim_visual_basic="dim value",
        directcast_visual_basic="directcast value",
        do_visual_basic="do value",
        double_visual_basic="double value",
        each_visual_basic="each value",
        else_visual_basic="else value",
        elseif_visual_basic="elseif value",
        end_visual_basic="end value",
        endif_visual_basic="endif value",
        enum_visual_basic="enum value",
        erase_visual_basic="erase value",
        error_visual_basic="error value",
        event_visual_basic="event value",
        exit_visual_basic="exit value",
        finally_visual_basic="finally value",
        for_visual_basic="for value",
        friend_visual_basic="friend value",
        function_visual_basic="function value",
        get_visual_basic="get value",
        gettype_visual_basic="gettype value",
        getxmlnamespace_visual_basic="getxmlnamespace value",
        global_visual_basic="global value",
        gosub_visual_basic="gosub value",
        goto_visual_basic="goto value",
        handles_visual_basic="handles value",
        if_visual_basic="if value",
        implements_visual_basic="implements value",
        imports_visual_basic="imports value",
        in_visual_basic="in value",
        inherits_visual_basic="inherits value",
        integer_visual_basic="integer value",
        interface_visual_basic="interface value",
        is_visual_basic="is value",
        isnot_visual_basic="isnot value",
        let_visual_basic="let value",
        lib_visual_basic="lib value",
        like_visual_basic="like value",
        long_visual_basic="long value",
        loop_visual_basic="loop value",
        me_visual_basic="me value",
        mod_visual_basic="mod value",
        module_visual_basic="module value",
        mustinherit_visual_basic="mustinherit value",
        mustoverride_visual_basic="mustoverride value",
        mybase_visual_basic="mybase value",
        myclass_visual_basic="myclass value",
        namespace_visual_basic="namespace value",
        narrowing_visual_basic="narrowing value",
        new_visual_basic="new value",
        next_visual_basic="next value",
        not_visual_basic="not value",
        nothing_visual_basic="nothing value",
        notinheritable_visual_basic="notinheritable value",
        notoverridable_visual_basic="notoverridable value",
        object_visual_basic="object value",
        of_visual_basic="of value",
        on_visual_basic="on value",
        operator_visual_basic="operator value",
        option_visual_basic="option value",
        optional_visual_basic="optional value",
        or_visual_basic="or value",
        orelse_visual_basic="orelse value",
        overloads_visual_basic="overloads value",
        overridable_visual_basic="overridable value",
        overrides_visual_basic="overrides value",
        paramarray_visual_basic="paramarray value",
        partial_visual_basic="partial value",
        private_visual_basic="private value",
        property_visual_basic="property value",
        protected_visual_basic="protected value",
        public_visual_basic="public value",
        raiseevent_visual_basic="raiseevent value",
        readonly_visual_basic="readonly value",
        redim_visual_basic="redim value",
        rem_visual_basic="rem value",
        removehandler_visual_basic="removehandler value",
        resume_visual_basic="resume value",
        return_visual_basic="return value",
        sbyte_visual_basic="sbyte value",
        select_visual_basic="select value",
        set_visual_basic="set value",
        shadows_visual_basic="shadows value",
        shared_visual_basic="shared value",
        short_visual_basic="short value",
        single_visual_basic="single value",
        static_visual_basic="static value",
        step_visual_basic="step value",
        stop_visual_basic="stop value",
        string_visual_basic="string value",
        structure_visual_basic="structure value",
        sub_visual_basic="sub value",
        synclock_visual_basic="synclock value",
        then_visual_basic="then value",
        throw_visual_basic="throw value",
        to_visual_basic="to value",
        try_visual_basic="try value",
        trycast_visual_basic="trycast value",
        type_visual_basic="type value",
        typeof_visual_basic="typeof value",
        uinteger_visual_basic="uinteger value",
        ulong_visual_basic="ulong value",
        ushort_visual_basic="ushort value",
        using_visual_basic="using value",
        variant_visual_basic="variant value",
        wend_visual_basic="wend value",
        when_visual_basic="when value",
        while_visual_basic="while value",
        widening_visual_basic="widening value",
        with_visual_basic="with value",
        withevents_visual_basic="withevents value",
        writeonly_visual_basic="writeonly value",
        xor_visual_basic="xor value",
    ) == [[""]]


def test_delete_vba_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.DELETE,
        url="http://localhost:8949/vba_restricted_keywords?addhandler=addhandler+value&addressof=addressof+value&alias=alias+value&and=and+value&andalso=andalso+value&as=as+value&attribute=attribute+value&boolean=boolean+value&byref=byref+value&byte=byte+value&byval=byval+value&call=call+value&case=case+value&catch=catch+value&cbool=cbool+value&cbyte=cbyte+value&cchar=cchar+value&cdate=cdate+value&cdbl=cdbl+value&cdec=cdec+value&char=char+value&cint=cint+value&class=class+value&clng=clng+value&cobj=cobj+value&const=const+value&continue=continue+value&csbyte=csbyte+value&cshort=cshort+value&csng=csng+value&cstr=cstr+value&ctype=ctype+value&cuint=cuint+value&culng=culng+value&currency=currency+value&cushort=cushort+value&date=date+value&decimal=decimal+value&declare=declare+value&default=default+value&delegate=delegate+value&dim=dim+value&directcast=directcast+value&do=do+value&double=double+value&each=each+value&else=else+value&elseif=elseif+value&end=end+value&endif=endif+value&enum=enum+value&erase=erase+value&error=error+value&event=event+value&exit=exit+value&finally=finally+value&for=for+value&friend=friend+value&function=function+value&get=get+value&gettype=gettype+value&getxmlnamespace=getxmlnamespace+value&global=global+value&gosub=gosub+value&goto=goto+value&handles=handles+value&if=if+value&implements=implements+value&imports=imports+value&in=in+value&inherits=inherits+value&integer=integer+value&interface=interface+value&is=is+value&isnot=isnot+value&let=let+value&lib=lib+value&like=like+value&long=long+value&loop=loop+value&me=me+value&mod=mod+value&module=module+value&mustinherit=mustinherit+value&mustoverride=mustoverride+value&mybase=mybase+value&myclass=myclass+value&namespace=namespace+value&narrowing=narrowing+value&new=new+value&next=next+value&not=not+value&nothing=nothing+value&notinheritable=notinheritable+value&notoverridable=notoverridable+value&object=object+value&of=of+value&on=on+value&operator=operator+value&option=option+value&optional=optional+value&or=or+value&orelse=orelse+value&overloads=overloads+value&overridable=overridable+value&overrides=overrides+value&paramarray=paramarray+value&partial=partial+value&private=private+value&property=property+value&protected=protected+value&public=public+value&raiseevent=raiseevent+value&readonly=readonly+value&redim=redim+value&rem=rem+value&removehandler=removehandler+value&resume=resume+value&return=return+value&sbyte=sbyte+value&select=select+value&set=set+value&shadows=shadows+value&shared=shared+value&short=short+value&single=single+value&static=static+value&step=step+value&stop=stop+value&string=string+value&structure=structure+value&sub=sub+value&synclock=synclock+value&then=then+value&throw=throw+value&to=to+value&try=try+value&trycast=trycast+value&type=type+value&typeof=typeof+value&uinteger=uinteger+value&ulong=ulong+value&ushort=ushort+value&using=using+value&variant=variant+value&wend=wend+value&when=when+value&while=while+value&widening=widening+value&with=with+value&withevents=withevents+value&writeonly=writeonly+value&xor=xor+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_delete_vba_restricted_keywords(
        addhandler_visual_basic="addhandler value",
        addressof_visual_basic="addressof value",
        alias_visual_basic="alias value",
        and_visual_basic="and value",
        andalso_visual_basic="andalso value",
        as_visual_basic="as value",
        attribute_visual_basic="attribute value",
        boolean_visual_basic="boolean value",
        byref_visual_basic="byref value",
        byte_visual_basic="byte value",
        byval_visual_basic="byval value",
        call_visual_basic="call value",
        case_visual_basic="case value",
        catch_visual_basic="catch value",
        cbool_visual_basic="cbool value",
        cbyte_visual_basic="cbyte value",
        cchar_visual_basic="cchar value",
        cdate_visual_basic="cdate value",
        cdbl_visual_basic="cdbl value",
        cdec_visual_basic="cdec value",
        char_visual_basic="char value",
        cint_visual_basic="cint value",
        class_visual_basic="class value",
        clng_visual_basic="clng value",
        cobj_visual_basic="cobj value",
        const_visual_basic="const value",
        continue_visual_basic="continue value",
        csbyte_visual_basic="csbyte value",
        cshort_visual_basic="cshort value",
        csng_visual_basic="csng value",
        cstr_visual_basic="cstr value",
        ctype_visual_basic="ctype value",
        cuint_visual_basic="cuint value",
        culng_visual_basic="culng value",
        currency_visual_basic="currency value",
        cushort_visual_basic="cushort value",
        date_visual_basic="date value",
        decimal_visual_basic="decimal value",
        declare_visual_basic="declare value",
        default_visual_basic="default value",
        delegate_visual_basic="delegate value",
        dim_visual_basic="dim value",
        directcast_visual_basic="directcast value",
        do_visual_basic="do value",
        double_visual_basic="double value",
        each_visual_basic="each value",
        else_visual_basic="else value",
        elseif_visual_basic="elseif value",
        end_visual_basic="end value",
        endif_visual_basic="endif value",
        enum_visual_basic="enum value",
        erase_visual_basic="erase value",
        error_visual_basic="error value",
        event_visual_basic="event value",
        exit_visual_basic="exit value",
        finally_visual_basic="finally value",
        for_visual_basic="for value",
        friend_visual_basic="friend value",
        function_visual_basic="function value",
        get_visual_basic="get value",
        gettype_visual_basic="gettype value",
        getxmlnamespace_visual_basic="getxmlnamespace value",
        global_visual_basic="global value",
        gosub_visual_basic="gosub value",
        goto_visual_basic="goto value",
        handles_visual_basic="handles value",
        if_visual_basic="if value",
        implements_visual_basic="implements value",
        imports_visual_basic="imports value",
        in_visual_basic="in value",
        inherits_visual_basic="inherits value",
        integer_visual_basic="integer value",
        interface_visual_basic="interface value",
        is_visual_basic="is value",
        isnot_visual_basic="isnot value",
        let_visual_basic="let value",
        lib_visual_basic="lib value",
        like_visual_basic="like value",
        long_visual_basic="long value",
        loop_visual_basic="loop value",
        me_visual_basic="me value",
        mod_visual_basic="mod value",
        module_visual_basic="module value",
        mustinherit_visual_basic="mustinherit value",
        mustoverride_visual_basic="mustoverride value",
        mybase_visual_basic="mybase value",
        myclass_visual_basic="myclass value",
        namespace_visual_basic="namespace value",
        narrowing_visual_basic="narrowing value",
        new_visual_basic="new value",
        next_visual_basic="next value",
        not_visual_basic="not value",
        nothing_visual_basic="nothing value",
        notinheritable_visual_basic="notinheritable value",
        notoverridable_visual_basic="notoverridable value",
        object_visual_basic="object value",
        of_visual_basic="of value",
        on_visual_basic="on value",
        operator_visual_basic="operator value",
        option_visual_basic="option value",
        optional_visual_basic="optional value",
        or_visual_basic="or value",
        orelse_visual_basic="orelse value",
        overloads_visual_basic="overloads value",
        overridable_visual_basic="overridable value",
        overrides_visual_basic="overrides value",
        paramarray_visual_basic="paramarray value",
        partial_visual_basic="partial value",
        private_visual_basic="private value",
        property_visual_basic="property value",
        protected_visual_basic="protected value",
        public_visual_basic="public value",
        raiseevent_visual_basic="raiseevent value",
        readonly_visual_basic="readonly value",
        redim_visual_basic="redim value",
        rem_visual_basic="rem value",
        removehandler_visual_basic="removehandler value",
        resume_visual_basic="resume value",
        return_visual_basic="return value",
        sbyte_visual_basic="sbyte value",
        select_visual_basic="select value",
        set_visual_basic="set value",
        shadows_visual_basic="shadows value",
        shared_visual_basic="shared value",
        short_visual_basic="short value",
        single_visual_basic="single value",
        static_visual_basic="static value",
        step_visual_basic="step value",
        stop_visual_basic="stop value",
        string_visual_basic="string value",
        structure_visual_basic="structure value",
        sub_visual_basic="sub value",
        synclock_visual_basic="synclock value",
        then_visual_basic="then value",
        throw_visual_basic="throw value",
        to_visual_basic="to value",
        try_visual_basic="try value",
        trycast_visual_basic="trycast value",
        type_visual_basic="type value",
        typeof_visual_basic="typeof value",
        uinteger_visual_basic="uinteger value",
        ulong_visual_basic="ulong value",
        ushort_visual_basic="ushort value",
        using_visual_basic="using value",
        variant_visual_basic="variant value",
        wend_visual_basic="wend value",
        when_visual_basic="when value",
        while_visual_basic="while value",
        widening_visual_basic="widening value",
        with_visual_basic="with value",
        withevents_visual_basic="withevents value",
        writeonly_visual_basic="writeonly value",
        xor_visual_basic="xor value",
    ) == [[""]]


def test_attribute_vba_restricted_keyword_in_uri_parameter(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.GET,
        url="http://localhost:8949/my_attribute_value/vba/restricted/keyword/in/uri/parameter",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_get_attribute_vba_restricted_keyword_in_uri_parameter(
        attribute_visual_basic="my_attribute_value"
    ) == [
        [""]
    ]


def test_get_python_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.GET,
        url="http://localhost:8949/python_restricted_keywords?with.a.dot=with.a.dot+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_get_python_restricted_keywords(
        with_a_dot="with.a.dot value"
    ) == [[""]]


def test_post_python_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.POST,
        url="http://localhost:8949/python_restricted_keywords?with.a.dot=with.a.dot+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_post_python_restricted_keywords(
        with_a_dot="with.a.dot value"
    ) == [[""]]


def test_put_python_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.PUT,
        url="http://localhost:8949/python_restricted_keywords?with.a.dot=with.a.dot+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_put_python_restricted_keywords(
        with_a_dot="with.a.dot value"
    ) == [[""]]


def test_delete_python_restricted_keywords(
    responses: RequestsMock, vba_keywords_service, tmpdir
):
    pyxelrestgenerator = loader.load(
        tmpdir,
        {
            "vba_keywords": {
                "open_api": {"definition": "http://localhost:8949/"},
                "udf": {"return_types": ["sync_auto_expand"], "shift_result": False},
            }
        },
    )
    responses.add(
        responses.DELETE,
        url="http://localhost:8949/python_restricted_keywords?with.a.dot=with.a.dot+value",
        json={},
        match_querystring=True,
    )

    assert pyxelrestgenerator.vba_keywords_delete_python_restricted_keywords(
        with_a_dot="with.a.dot value"
    ) == [[""]]
